services:
  dashboard-web:
    build: .
    container_name: crm-dashboard-web
    restart: always
    volumes:
      - ./files:/app/files
      - ./templates:/app/templates
    environment:
      - DATABASE_URL=postgresql://admin:crm_Mot2P%40sse@crm-postgres:5432/crm_db
      - SESSION_SECRET=${SESSION_SECRET}
      - DEFAULT_ENTREPRISE_ID=${DEFAULT_ENTREPRISE_ID:-1}
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      # --- LIGNE CRUCIALE ---
      - "traefik.docker.network=n8n_default"
      # ----------------------
      - "traefik.http.routers.crm-dash.rule=Host(`dashboard.mrliw.fr`)"
      - "traefik.http.routers.crm-dash.entrypoints=websecure"
      - "traefik.http.routers.crm-dash.tls=true"
      - "traefik.http.routers.crm-dash.tls.certresolver=myresolver"
      - "traefik.http.services.crm-dash.loadbalancer.server.port=8000"

networks:
  n8n_default:
    external: true
